name: shared
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  translations:
    path: ../translations
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  provider: ^6.1.4
  http: ^1.2.2
  cached_network_image: ^3.4.1
  intl: ^0.20.2
  freezed: ^2.5.7
  freezed_annotation: ^2.4.4
  json_annotation: ^4.9.0
  flutter_svg: ^2.0.16
  flutter_easyloading: ^3.0.5
  carousel_slider: ^5.0.0
  animate_do: ^4.2.0
  scrollable_positioned_list: ^0.3.8
  google_sign_in: ^6.3.0
  crypto: ^3.0.6
  sign_in_with_apple: ^6.1.4
  shared_preferences: ^2.5.3
  fluttertoast: ^8.2.8
  geolocator: ^13.0.4
  uuid: ^4.5.1
  google_maps_flutter: ^2.12.1
  path: ^1.9.0
  path_provider: ^2.1.5
  hexcolor: ^3.0.1
  flutter_rating_bar: ^4.0.1
  flutter_html: ^3.0.0
  rxdart: ^0.28.0
  flutter_slidable: ^4.0.0
  infinite_scroll_pagination: ^5.0.0
  collection: ^1.19.1
  flutter_cupertino_datetime_picker: ^3.0.0
  auto_size_text: ^3.0.0
  flutter_stripe: ^11.5.0
  flutter_dotenv: ^5.2.1
  # share_plus: ^11.0.0
  animated_flip_counter: ^0.3.4
  url_launcher: ^6.3.1
  timeago: ^3.7.1
  get_it: ^8.0.3
  toggle_switch: ^2.3.0
  skeletonizer: ^2.0.1
  flutter_branch_sdk: ^8.5.0
  smooth_page_indicator: ^1.2.1
  flutter_staggered_grid_view: ^0.7.0
  animated_theme_switcher: ^2.0.10
  pin_code_fields: ^8.0.1
  sendotp_flutter_sdk: ^0.0.1
  go_router: ^15.1.0
  flutter_quill: ^11.2.0
  flutter_quill_delta_from_html: ^1.4.1
  vsc_quill_delta_to_html: ^1.0.5
  url_strategy: ^0.2.0
  flutter_local_notifications: ^19.3.0
  widget_to_marker: ^1.0.6
  easy_stepper: ^0.8.5+1
  syncfusion_flutter_charts: ^30.1.40
  flutter_date_range_picker: ^0.2.1
  get_storage: ^2.1.1
  typesense: ^0.5.2

  #google
  googleapis: ^14.0.0
  googleapis_auth: ^2.0.0
  vertex_ai: ^0.1.2

  #firebase
  firebase_core: ^4.0.0
  cloud_firestore: ^6.0.0
  firebase_auth: ^6.0.1
  firebase_messaging: ^16.0.0
  firebase_analytics: ^12.0.0
  firebase_ui_firestore: ^2.0.0
  firebase_storage: ^13.0.0
  cloud_functions: ^6.0.0

  #Algolia
  algolia_client_recommend: ^1.32.0
  algoliasearch: ^1.30.2
  algolia_helper_flutter: ^1.2.0
  algolia_insights: ^1.0.2
  font_awesome_flutter:
    git:
      url: https://github.com/kawad852/font_awesome_flutter.git


dev_dependencies:
  build_runner: ^2.4.11
  json_serializable: ^6.8.0
  go_router_builder: ^2.9.0
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  assets:
    - ../../assets/
  #
  # For details regarding assets in packages, see
  # https://flutter.dev/to/asset-from-package
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # To add custom fonts to your package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/to/font-from-package
