class AlgoliaDummyData {
  Map<String, dynamic> get categoryProducts => {
    "hits": [
      {
        "_tags": [],
        "_geoloc": {"lat": 0, "lng": 0},
        "basePrice": 1999.81,
        "brand": {"id": "brand_7", "name": "Gucci"},
        "categoryIds": ["grocieries"],
        "createdAt": "2025-07-05T08:52:37.259231",
        "descriptionAr": "وصف: Essential grocery item for your kitchen.",
        "descriptionEn": "Essential grocery item for your kitchen.",
        "discountPercent": 0,
        "finalPrice": 1999.81,
        "id": "product_87",
        "inStock": true,
        "isOnSale": false,
        "nameAr": "ترجمة Eggs",
        "nameEn": "Eggs",
        "published": true,
        "purchasesCount": 400,
        "rating": {"average": 4.9, "count": 425},
        "stockQuantity": 8,
        "trendingScore": 97,
        "viewsCount": 5003,
        "path": "products/product_87",
        "objectID": "product_87",
        "_highlightResult": {
          "basePrice": {"value": "1999.81", "matchLevel": "none", "matchedWords": []},
          "brand": {
            "id": {"value": "brand_7", "matchLevel": "none", "matchedWords": []},
            "name": {"value": "Gucci", "matchLevel": "none", "matchedWords": []},
          },
          "categoryIds": [
            {"value": "grocieries", "matchLevel": "none", "matchedWords": []},
          ],
          "createdAt": {
            "value": "2025-07-05T08:52:37.259231",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionAr": {
            "value": "وصف: Essential grocery item for your kitchen.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionEn": {
            "value": "Essential grocery item for your kitchen.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "discountPercent": {"value": "0", "matchLevel": "none", "matchedWords": []},
          "finalPrice": {"value": "1999.81", "matchLevel": "none", "matchedWords": []},
          "id": {"value": "product_87", "matchLevel": "none", "matchedWords": []},
          "nameAr": {"value": "ترجمة Eggs", "matchLevel": "none", "matchedWords": []},
          "nameEn": {"value": "Eggs", "matchLevel": "none", "matchedWords": []},
          "purchasesCount": {"value": "400", "matchLevel": "none", "matchedWords": []},
          "rating": {
            "average": {"value": "4.9", "matchLevel": "none", "matchedWords": []},
            "count": {"value": "425", "matchLevel": "none", "matchedWords": []},
          },
          "stockQuantity": {"value": "8", "matchLevel": "none", "matchedWords": []},
          "trendingScore": {"value": "97", "matchLevel": "none", "matchedWords": []},
          "viewsCount": {"value": "5003", "matchLevel": "none", "matchedWords": []},
          "path": {"value": "products/product_87", "matchLevel": "none", "matchedWords": []},
        },
      },
      {
        "_tags": ["best_seller"],
        "_geoloc": {"lat": 0, "lng": 0},
        "basePrice": 1963.87,
        "brand": {"id": "brand_8", "name": "LG"},
        "categoryIds": ["bags"],
        "createdAt": "2025-07-05T08:52:37.259273",
        "descriptionAr": "وصف: Durable and spacious bag for travel, work or school.",
        "descriptionEn": "Durable and spacious bag for travel, work or school.",
        "discountPercent": 0,
        "finalPrice": 1963.87,
        "id": "product_90",
        "inStock": false,
        "isOnSale": false,
        "nameAr": "ترجمة Nike Gym Bag",
        "nameEn": "Nike Gym Bag",
        "published": true,
        "purchasesCount": 130,
        "rating": {"average": 2.6, "count": 834},
        "stockQuantity": 78,
        "trendingScore": 88,
        "viewsCount": 1329,
        "path": "products/product_90",
        "objectID": "product_90",
        "_highlightResult": {
          "_tags": [
            {"value": "best_seller", "matchLevel": "none", "matchedWords": []},
          ],
          "basePrice": {"value": "1963.87", "matchLevel": "none", "matchedWords": []},
          "brand": {
            "id": {"value": "brand_8", "matchLevel": "none", "matchedWords": []},
            "name": {"value": "LG", "matchLevel": "none", "matchedWords": []},
          },
          "categoryIds": [
            {"value": "bags", "matchLevel": "none", "matchedWords": []},
          ],
          "createdAt": {
            "value": "2025-07-05T08:52:37.259273",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionAr": {
            "value": "وصف: Durable and spacious bag for travel, work or school.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionEn": {
            "value": "Durable and spacious bag for travel, work or school.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "discountPercent": {"value": "0", "matchLevel": "none", "matchedWords": []},
          "finalPrice": {"value": "1963.87", "matchLevel": "none", "matchedWords": []},
          "id": {"value": "product_90", "matchLevel": "none", "matchedWords": []},
          "nameAr": {"value": "ترجمة Nike Gym Bag", "matchLevel": "none", "matchedWords": []},
          "nameEn": {"value": "Nike Gym Bag", "matchLevel": "none", "matchedWords": []},
          "purchasesCount": {"value": "130", "matchLevel": "none", "matchedWords": []},
          "rating": {
            "average": {"value": "2.6", "matchLevel": "none", "matchedWords": []},
            "count": {"value": "834", "matchLevel": "none", "matchedWords": []},
          },
          "stockQuantity": {"value": "78", "matchLevel": "none", "matchedWords": []},
          "trendingScore": {"value": "88", "matchLevel": "none", "matchedWords": []},
          "viewsCount": {"value": "1329", "matchLevel": "none", "matchedWords": []},
          "path": {"value": "products/product_90", "matchLevel": "none", "matchedWords": []},
        },
      },
      {
        "_tags": [],
        "_geoloc": {"lat": 0, "lng": 0},
        "basePrice": 1838.16,
        "brand": {"id": "brand_5", "name": "Apple"},
        "categoryIds": ["bags"],
        "createdAt": "2025-07-05T08:52:37.258336",
        "descriptionAr": "وصف: Durable and spacious bag for travel, work or school.",
        "descriptionEn": "Durable and spacious bag for travel, work or school.",
        "discountPercent": 0,
        "finalPrice": 1838.16,
        "id": "product_29",
        "inStock": false,
        "isOnSale": false,
        "nameAr": "ترجمة Nike Gym Bag",
        "nameEn": "Nike Gym Bag",
        "published": true,
        "purchasesCount": 228,
        "rating": {"average": 2.4, "count": 93},
        "stockQuantity": 60,
        "trendingScore": 24,
        "viewsCount": 7578,
        "path": "products/product_29",
        "objectID": "product_29",
        "_highlightResult": {
          "basePrice": {"value": "1838.16", "matchLevel": "none", "matchedWords": []},
          "brand": {
            "id": {"value": "brand_5", "matchLevel": "none", "matchedWords": []},
            "name": {"value": "Apple", "matchLevel": "none", "matchedWords": []},
          },
          "categoryIds": [
            {"value": "bags", "matchLevel": "none", "matchedWords": []},
          ],
          "createdAt": {
            "value": "2025-07-05T08:52:37.258336",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionAr": {
            "value": "وصف: Durable and spacious bag for travel, work or school.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionEn": {
            "value": "Durable and spacious bag for travel, work or school.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "discountPercent": {"value": "0", "matchLevel": "none", "matchedWords": []},
          "finalPrice": {"value": "1838.16", "matchLevel": "none", "matchedWords": []},
          "id": {"value": "product_29", "matchLevel": "none", "matchedWords": []},
          "nameAr": {"value": "ترجمة Nike Gym Bag", "matchLevel": "none", "matchedWords": []},
          "nameEn": {"value": "Nike Gym Bag", "matchLevel": "none", "matchedWords": []},
          "purchasesCount": {"value": "228", "matchLevel": "none", "matchedWords": []},
          "rating": {
            "average": {"value": "2.4", "matchLevel": "none", "matchedWords": []},
            "count": {"value": "93", "matchLevel": "none", "matchedWords": []},
          },
          "stockQuantity": {"value": "60", "matchLevel": "none", "matchedWords": []},
          "trendingScore": {"value": "24", "matchLevel": "none", "matchedWords": []},
          "viewsCount": {"value": "7578", "matchLevel": "none", "matchedWords": []},
          "path": {"value": "products/product_29", "matchLevel": "none", "matchedWords": []},
        },
      },
      {
        "_tags": [],
        "_geoloc": {"lat": 0, "lng": 0},
        "basePrice": 1807.49,
        "brand": {"id": "brand_3", "name": "Nike"},
        "categoryIds": ["toys"],
        "createdAt": "2025-07-05T08:52:37.258091",
        "descriptionAr": "وصف: Fun and educational toy for children of all ages.",
        "descriptionEn": "Fun and educational toy for children of all ages.",
        "discountPercent": 0,
        "finalPrice": 1807.49,
        "id": "product_13",
        "inStock": true,
        "isOnSale": false,
        "nameAr": "ترجمة Barbie Dreamhouse",
        "nameEn": "Barbie Dreamhouse",
        "published": true,
        "purchasesCount": 299,
        "rating": {"average": 1.5, "count": 664},
        "stockQuantity": 93,
        "trendingScore": 45,
        "viewsCount": 8198,
        "path": "products/product_13",
        "objectID": "product_13",
        "_highlightResult": {
          "basePrice": {"value": "1807.49", "matchLevel": "none", "matchedWords": []},
          "brand": {
            "id": {"value": "brand_3", "matchLevel": "none", "matchedWords": []},
            "name": {"value": "Nike", "matchLevel": "none", "matchedWords": []},
          },
          "categoryIds": [
            {"value": "toys", "matchLevel": "none", "matchedWords": []},
          ],
          "createdAt": {
            "value": "2025-07-05T08:52:37.258091",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionAr": {
            "value": "وصف: Fun and educational toy for children of all ages.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "descriptionEn": {
            "value": "Fun and educational toy for children of all ages.",
            "matchLevel": "none",
            "matchedWords": [],
          },
          "discountPercent": {"value": "0", "matchLevel": "none", "matchedWords": []},
          "finalPrice": {"value": "1807.49", "matchLevel": "none", "matchedWords": []},
          "id": {"value": "product_13", "matchLevel": "none", "matchedWords": []},
          "nameAr": {"value": "ترجمة Barbie Dreamhouse", "matchLevel": "none", "matchedWords": []},
          "nameEn": {"value": "Barbie Dreamhouse", "matchLevel": "none", "matchedWords": []},
          "purchasesCount": {"value": "299", "matchLevel": "none", "matchedWords": []},
          "rating": {
            "average": {"value": "1.5", "matchLevel": "none", "matchedWords": []},
            "count": {"value": "664", "matchLevel": "none", "matchedWords": []},
          },
          "stockQuantity": {"value": "93", "matchLevel": "none", "matchedWords": []},
          "trendingScore": {"value": "45", "matchLevel": "none", "matchedWords": []},
          "viewsCount": {"value": "8198", "matchLevel": "none", "matchedWords": []},
          "path": {"value": "products/product_13", "matchLevel": "none", "matchedWords": []},
        },
      },
    ],
    "nbHits": 100,
    "page": 0,
    "nbPages": 5,
    "hitsPerPage": 20,
    "facets": {
      "_tags": {
        "best_seller": 21,
        "limited_offer": 22,
        "new_arrival": 20,
        "summer_sale": 19,
        "trending": 22,
      },
      "categoryIds": {
        "accessories": 5,
        "bags": 10,
        "cars": 7,
        "clothing": 5,
        "food": 7,
        "furniture": 2,
        "grocieries": 3,
        "headphones": 6,
        "jobs": 6,
        "laptops": 12,
        "pets": 4,
        "phones": 5,
        "real_estates": 3,
        "shoes": 7,
        "shopping": 5,
        "toys": 7,
        "watches": 6,
      },
      "finalPrice": {
        "182": 1,
        "713": 1,
        "1006.55": 1,
        "1015.7": 1,
        "1037.59": 1,
        "1047.43": 1,
        "1047.87": 1,
        "1127.94": 1,
        "1155.67": 1,
        "1163.6": 1,
        "1179.67": 1,
        "1245.42": 1,
        "1252.78": 1,
        "127.26": 1,
        "1272.78": 1,
        "1296.56": 1,
        "13.43": 1,
        "1318.54": 1,
        "1351.13": 1,
        "1423.68": 1,
        "1428.92": 1,
        "145.95": 1,
        "1548.18": 1,
        "1585.78": 1,
        "160.34": 1,
        "1644.26": 1,
        "166.32": 1,
        "1696.4": 1,
        "1706.56": 1,
        "172.63": 1,
        "1721.03": 1,
        "1728.77": 1,
        "1762.97": 1,
        "1773.15": 1,
        "1785.71": 1,
        "1805.06": 1,
        "1806.98": 1,
        "1807.49": 1,
        "1838.16": 1,
        "191.73": 1,
        "192.59": 1,
        "1963.87": 1,
        "1999.81": 1,
        "246.23": 1,
        "251.13": 1,
        "292.58": 1,
        "298.44": 1,
        "299.02": 1,
        "319.68": 1,
        "322.76": 1,
        "336.02": 1,
        "356.49": 1,
        "372.53": 1,
        "38.82": 1,
        "398.24": 1,
        "410.06": 1,
        "420.7": 1,
        "439.87": 1,
        "444.15": 1,
        "448.72": 1,
        "450.06": 1,
        "452.61": 1,
        "454.74": 1,
        "463.93": 1,
        "467.05": 1,
        "474.28": 1,
        "515.75": 1,
        "521.06": 1,
        "552.53": 1,
        "554.86": 1,
        "554.91": 1,
        "581.47": 1,
        "592.91": 1,
        "602.58": 1,
        "620.96": 1,
        "627.4": 1,
        "650.27": 1,
        "650.91": 1,
        "657.65": 1,
        "667.06": 1,
        "683.98": 1,
        "751.04": 1,
        "761.03": 1,
        "763.53": 1,
        "782.52": 1,
        "790.79": 1,
        "810.07": 1,
        "824.95": 1,
        "827.72": 1,
        "829.12": 1,
        "865.73": 1,
        "873.16": 1,
        "878.32": 1,
        "880.25": 1,
        "918.65": 1,
        "92.19": 1,
        "92.95": 1,
        "956.92": 1,
        "965.89": 1,
        "985.13": 1,
      },
    },
    "facets_stats": {
      "finalPrice": {"min": 13.43, "max": 1999.81, "avg": 827.536, "sum": 82753.6},
    },
    "exhaustiveFacetsCount": true,
    "exhaustiveNbHits": true,
    "exhaustiveTypo": true,
    "exhaustive": {"facetsCount": true, "nbHits": true, "typo": true},
    "query": "",
    "params":
        "facets=%5B%22*%22%5D&page=0&userToken=HZVJiTSVFPNTiy36RBALXq6Yv1G3&clickAnalytics=true&analytics=true&hitsPerPage=20",
    "index": "products",
    "queryID": "d3766c5c378c1d20aa9c45642cda8913",
    "renderingContent": {
      "facetOrdering": {
        "facets": {
          "order": [
            "trending",
            "categoryIds",
            "deviceType",
            "discountPrice",
            "rating.average",
            "finalPrice",
          ],
        },
        "values": {
          "categoryIds": {"sortRemainingBy": "count"},
          "deviceType": {
            "order": ["TABLET", "MOBILE", "LAPTOP"],
            "sortRemainingBy": "count",
          },
          "discountPrice": {"sortRemainingBy": "count"},
          "finalPrice": {"sortRemainingBy": "count"},
          "rating.average": {"sortRemainingBy": "count"},
          "trending": {"sortRemainingBy": "count"},
        },
      },
    },
    "processingTimeMS": 1,
    "processingTimingsMS": {
      "_request": {"roundTrip": 65},
      "total": 1,
    },
    "serverTimeMS": 2,
  };
}
