// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDIjeRgsBq5-UdaXG_A5XPBwvqVrfSygjw',
    appId: '1:943748837802:web:3dbae754684dad9c5d3bd3',
    messagingSenderId: '943748837802',
    projectId: 'minutto-app',
    authDomain: 'minutto-app.firebaseapp.com',
    storageBucket: 'minutto-app.firebasestorage.app',
    measurementId: 'G-G9455WFY9P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATzFWbCodEmjAOCK3MboZ3vUwfyIDUa4Y',
    appId: '1:943748837802:android:a05772acc0366aa75d3bd3',
    messagingSenderId: '943748837802',
    projectId: 'minutto-app',
    storageBucket: 'minutto-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmnzo3Dv3WT4knGpx9Kue4wDzYNVroN7I',
    appId: '1:943748837802:ios:f6cad717b86d19825d3bd3',
    messagingSenderId: '943748837802',
    projectId: 'minutto-app',
    storageBucket: 'minutto-app.firebasestorage.app',
    iosBundleId: 'com.minutto.wecan',
  );

}